<?php
// $Id: user_karma_receive_vote_comment.install,v 1.1.2.1.2.1 2008/09/05 09:05:10 sicjoy Exp $

/**
 * @file
 */
 
/*
 * Implementation of hook_install().
 */
function user_karma_receive_vote_comment_install() {}

/*
 * Implementation of hook_uninstall().
 */
function user_karma_receive_vote_comment_uninstall() {
  variable_del('user_karma_receive_vote_comment_activate');
  variable_del('user_karma_receive_vote_comment_content_types');
  variable_del('user_karma_receive_vote_comment_karma_multiplier');
  variable_del('user_karma_receive_vote_comment_value_types');
}
